#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -u

source .fonctions	# Charge les fonctions génériques habituellement utilisées dans le script

# Source app helpers
source /usr/share/yunohost/helpers

# Get application informations
app=$YNH_APP_INSTANCE_NAME
domain=$(ynh_app_setting_get $app domain)

SECURE_REMOVE '/var/www/$app'
#SECURE_REMOVE '/var/log/$app'

sudo systemctl stop concerteur.service

# If a MySQL database is used:
# Drop MySQL database and user
dbname=$app
dbuser=$app
ynh_mysql_drop_db "$dbname" || true
ynh_mysql_drop_user "$dbuser" || true
# MySQL end ###

SECURE_REMOVE '/etc/systemd/system/concercerteur.service'
if [ -e "/etc/systemd/system/concercerteur.service" ]; then
	sudo rm -fr '/etc/systemd/system/concercerteur.service'
fi

REMOVE_NGINX_CONF # Suppression de la configuration nginx
